<?php
    namespace Bearlovescode\Activitypub\Providers;

    use Illuminate\Support\ServiceProvider;

    class ActivitypubServiceProvider extends ServiceProvider
    {
        public function boot() {}
        public function register()
        {
            parent::register(); // TODO: Change the autogenerated stub

            $this->loadRoutesFrom(__DIR__ . '../../routes/web.php');
        }
    }